### ISSUE TITLE
globalThis not working within workers-override.ts

### ISSUE THREAD

**Issue by dominikzach** [cloudflare/worker-template-mysql#1]
Hallo,
thanks for this template. I tried it out and without a Tunnel Security set, it works.

Now i want to secure my tunnel so i need to set the:
globalThis.CF_CLIENT_ID
and
globalThis.CF_CLIENT_SECRET
Like in the template said. 

The 'globalThis' works fine in the normal worker template i can set and get out of it.

BUT those 'globalThis' does not work in the 'workers-override.ts' where the Headers to the tunnel get setted.

![grafik](https://user-images.githubusercontent.com/50666366/146387072-3d761e08-5f1b-471b-9658-8a93eda71914.png)

**Comment by nilslice** [comment]
@dominikzach - thank you for pointing this out. An update has been made to the template which should fix this! Please re-open the issue if that is not the case.
